Important Dependenties:

In [24]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

Data Collection and Analysis


PIMA Diabetes Dataset

In [4]:
# Loading the data from Pandas DataFrames:
diabetes_dataset = pd.read_csv('Diabetes.csv')

In [8]:
# Printing the first 5 rows of the dataset:
diabetes_dataset.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Diagnosis
0,2,115.863387,56.410731,24.336736,94.385783,26.455940,0.272682,20.100494,0
1,2,92.490122,70.615520,23.443591,138.652426,23.910167,0.665160,44.912281,0
2,1,88.141469,63.262618,23.404364,149.358082,21.948250,0.676022,48.247873,1
3,2,108.453101,67.793632,20.751580,108.751638,24.209304,0.289636,42.749868,0
4,1,127.849443,94.725685,22.603078,25.269987,32.997477,0.601315,32.797789,0

In [11]:
# Getting the statistical measures of the data
diabetes_dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Diagnosis
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000
mean,1.771000,99.440607,72.179837,23.278316,84.582679,25.433600,0.449383,43.281798,0.30600
std,1.354398,19.470730,13.882017,1.173807,74.872733,3.690223,0.199334,14.465398,0.46106
min,0.000000,30.571402,31.401487,19.369987,-165.310033,13.548818,0.100037,-0.979804,0.00000
25%,1.000000,86.145927,62.795447,22.501591,35.076535,23.022715,0.283376,33.518451,0.00000
50%,2.000000,99.458362,71.909588,23.275225,84.442232,25.455649,0.448219,43.634273,0.00000
75%,3.000000,113.264556,82.082660,24.052022,134.267842,27.972184,0.619158,53.098446,1.00000
max,8.000000,161.238939,110.723715,26.917654,317.701852,36.324598,0.799654,90.573782,1.00000

In [7]:
diabetes_dataset.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Diagnosis                   0
dtype: int64

In [10]:
# The Number of rows and Columns in this dataset
diabetes_dataset.shape

(1000, 9)

In [13]:
diabetes_dataset['Diagnosis'].value_counts()

Diagnosis
0    694
1    306
Name: count, dtype: int64

0--> Non-Diabetic




1-->Diabetic

In [14]:
diabetes_dataset.groupby('Diagnosis').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Diagnosis,,,,,,,,
0,1.772334,99.504846,72.084485,23.278327,82.823035,25.515244,0.441372,43.711192
1,1.767974,99.294917,72.396092,23.278291,88.573505,25.248433,0.467550,42.307942

In [15]:
# Separating the data and labels:
X = diabetes_dataset.drop(columns = 'Diagnosis', axis=1)
Y = diabetes_dataset['Diagnosis']

In [16]:
print(X)

     Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
0              2  115.863387      56.410731      24.336736   94.385783
1              2   92.490122      70.615520      23.443591  138.652426
2              1   88.141469      63.262618      23.404364  149.358082
3              2  108.453101      67.793632      20.751580  108.751638
4              1  127.849443      94.725685      22.603078   25.269987
..           ...         ...            ...            ...         ...
995            1  103.496355      41.059401      24.930299   43.675978
996            1   60.714150      64.082842      24.689064  111.562745
997            0   97.597727      64.122312      22.140339  108.138552
998            0   66.775137      55.908797      24.885274  219.521484
999            0   87.647268      69.111593      25.621266  134.335745

           BMI  DiabetesPedigreeFunction        Age
0    26.455940                  0.272682  20.100494
1    23.910167                  0.665160  44.912281
2    21.948250                  0.676022  48.247873
3    24.209304                  0.289636  42.749868
4    32.997477                  0.601315  32.797789
..         ...                       ...        ...
995  25.846062                  0.455884  19.905419
996  19.464280                  0.250560  44.421874
997  22.733052                  0.761463  58.949800
998  31.819187                  0.382877  46.928923
999  31.098746                  0.605828  41.785889

[1000 rows x 8 columns]

In [17]:
print(Y)

0      0
1      0
2      1
3      0
4      0
      ..
995    0
996    1
997    1
998    0
999    1
Name: Diagnosis, Length: 1000, dtype: int64

Data Standarization

In [28]:
scaler = StandardScaler()

In [30]:
scaler.fit(X)

StandardScaler()

In [32]:
standarized_data = scaler.transform(X)

In [33]:

print(standarized_data)

[[ 0.16916344  0.84388194 -1.13650602 ...  0.27717891 -0.88689813
  -1.60333665]
 [ 0.16916344 -0.35714958 -0.11274294 ... -0.41303606  1.08302816
   0.11277251]
 [-0.56954153 -0.58060442 -0.64267896 ... -0.94495457  1.13754671
   0.34347898]
 ...
 [-1.30824649 -0.09469611 -0.58071939 ... -0.73217763  1.56639535
   1.08367856]
 [-1.30824649 -1.67851002 -1.17268119 ...  1.73127265 -0.33380688
   0.25225371]
 [-1.30824649 -0.60599888 -0.2211335  ...  1.53594517  0.78523145
  -0.10346468]]

In [34]:
X = standarized_data
Y = diabetes_dataset['Diagnosis']

In [35]:
print(X)
print(Y)

[[ 0.16916344  0.84388194 -1.13650602 ...  0.27717891 -0.88689813
  -1.60333665]
 [ 0.16916344 -0.35714958 -0.11274294 ... -0.41303606  1.08302816
   0.11277251]
 [-0.56954153 -0.58060442 -0.64267896 ... -0.94495457  1.13754671
   0.34347898]
 ...
 [-1.30824649 -0.09469611 -0.58071939 ... -0.73217763  1.56639535
   1.08367856]
 [-1.30824649 -1.67851002 -1.17268119 ...  1.73127265 -0.33380688
   0.25225371]
 [-1.30824649 -0.60599888 -0.2211335  ...  1.53594517  0.78523145
  -0.10346468]]
0      0
1      0
2      1
3      0
4      0
      ..
995    0
996    1
997    1
998    0
999    1
Name: Diagnosis, Length: 1000, dtype: int64

Train Test Split

In [36]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, stratify=Y, random_state=2)

In [38]:
print(X.shape, X_train.shape,X_test.shape)

(1000, 8) (800, 8) (200, 8)

Trainig the Model

In [45]:
classifier = svm.SVC(kernel='linear')

In [46]:
# Training the support vector Machine Classifier

classifier.fit(X_train, Y_train)

SVC(kernel='linear')

Model Evaluation







Accuracy Score

In [47]:
# Accuracy Score on the training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy =accuracy_score(X_train_prediction, Y_train)

In [48]:
print('Accuracy on the traning data :', training_data_accuracy)

Accuracy on the traning data : 0.69375

In [49]:
# Accuracy on the testing data
X_test_prediction = classifier.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [50]:
print('Accuracy on the testing data :',testing_data_accuracy)

Accuracy on the testing data : 0.695

Make a predictive Sysytem

In [55]:
input_data =(105.92369609462027,57.14189055603926,22.487371714816046,25.26130427518649,25.308670168185508,0.6379274569648937,25.779578937091728,1)

# Changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)

# standarize the input data
std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)


if(prediction[0] ==0):
    print('The Person is not diabetic')
else:
    print('The Person is diabetic')

[[ 76.93811356  -2.17351285  -3.58141963   1.69021042  -0.79205961
   -6.72264968 127.13744536  -2.92442383]]
[0]
The Person is not diabetic

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(